// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhoomhcubcprawzwxyok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ob29taGN1YmNwcmF3end4eW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDQ5MjcsImV4cCI6MjA2NzUyMDkyN30.RwED-qIHE8iRLfYJh2yl0mGTd8oI7noGSmRHY6vOmmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});